### ISSUE TITLE
Add auction commands

### ISSUE THREAD

**Issue by ricmoo** [ricmoo/ethers-meow#1]
**API**

```
Manager.prototype.bidOnSale(kittyId);
Manager.prototype.startSaleAuction(kittyId, startPrice, endPrice, duration);
Manager.prototype.cancelSaleAuction(kittyId);

Manager.prototype.bidOnSiring(kittyId);
Manager.prototype.startSiringAuction(kittyId, startPrice, endPrice, duration);
Manager.prototype.cancelSiringAuction(kittyId);
```

**Command-Line Interface**

```
sale-bid KITTY_ID
sale-auction KITTY_ID START_PRICE END_PRICE DURATION
sale-cancel KITTY_ID

sire-bid KITTY_ID
sire-auction KITTY_ID START_PRICE END_PRICE DURATION
sire-cancel KITTY_ID
```

**Other things:**
- Add current price to lookup

**Comment by chenyin** [comment]
It would be great to have this feature. I found meow is the best command line/ API interface to cryptokitties currently.

**Comment by ricmoo** [comment]
They are complete, and I use the `sale-create` a lot myself. The transaction fees are too high for me to properly test right now though, and I would rather test before releasing. :)

I've been asking if there is a Ropsten deployment, but no luck so far. Do you know if there is a Ropsten deployment might be?

**Comment by chenyin** [comment]
No. But I can test it on main network for you. Can you create a branch for me to test?

**Comment by ricmoo** [comment]
Thanks for the offer!

I've decided to bite the bullet and test this shortly and should have this up within an hour or so.

**Comment by ricmoo** [comment]
This has been tested and is now published to npm. To update to the latest version:

```
/home/ricmoo> npm install -g ethers-meow
```

Thanks! :)
