### ISSUE TITLE
Is this using the CryptoKitties API or is it actually using Raw commands

### ISSUE THREAD

**Issue by hscanlan** [ricmoo/ethers-meow#11]
Are these calls going to the cryptokitties API, or are they just doing raw commands ?

**Comment by ricmoo** [comment]
This communicates directly with the Blockchain by using the default ethers.js provider, which connects to both Etherscan API and the INFURA backends.

**Comment by hscanlan** [comment]
That's awesome.

So how did you figure out what the JSON was for the communication?

I'm working on a .NET CORE implementation, but basically using your code as a base. I'm just starting with Transfers to get going.

I'm new to the blockchain, so forgive me. I'm using a package already (Nethereum) to communicate with the Blockchain, I'm just not sure what to send for data to make the transaction work...

**Comment by hscanlan** [comment]
I'm guessing TokenID == KittyID .. and the rest is just the wallet addresses... but how do you test if the data is formatted correctly? How are you testing? You must be going through a s**t load of gas.

**Comment by ricmoo** [comment]
Which JSON? This is all backed on top of my ethers.js library, which handles all the binary encoding/decoding against the calls to the blockchain EVM.

Yes, `kittyId` is the `tokenId`, the `tokenId` calls are based on the ERC-271 API calls, but the CK specific calls tend to use kittyId, which I think is more descriptive. That said, the names don't really matter as they are only used in the API specification and not used on chain at all.

It did cost about $30 in testing. :p
