### ISSUE TITLE
Is there a way to find out who gifted you a kitty?

### ISSUE THREAD

**Issue by hscanlan** [ricmoo/ethers-meow#13]
I was curious if there was a way to find out who gifted you a kitty?

**Comment by ricmoo** [comment]
Not easily. You could list all transfer events and look for your address or the kittyId in question.

I am working on a tool to make this much simpler though. :)

**Comment by hscanlan** [comment]
I figured as such. I basically did exactly what you said .. thought there was an easier way ..
