### ISSUE TITLE
functions without cost

### ISSUE THREAD

**Issue by laudney** [ricmoo/ethers-meow#14]
I have a silly question. It seems that your code is calling certain functions in the Core contract without a wallet or sending ethers, e.g. getKitty and getStatus.

Is this the case? And how can this be?

Thanks.

**Comment by ricmoo** [comment]
Those are read-only (i.e. constant) functions and require no ether to call. you only require ether for transaction which change the state (update values, remove values or add values).

This is why ethers.js makes a distinction between a signer (like a Wallet) and a mere provider.

**Comment by laudney** [comment]
Ahh. Thank you!
