### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by bitcoinrate** [ricmoo/ethers-meow#8]
I followed your instructions but got a load of error messages when the install runs.

MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\User
s\a\AppData\Roaming\npm\node_modules\ethers-meow\node_modules\sha3\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\a\AppData\Roaming\npm\node_modules\ethers-meow\node_modules\sha3
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Any help?

Thanks to dev for sharing, great work!

**Comment by ricmoo** [comment]
I'm not terribly familiar with Windows, but it looks like maybe node-gyp (which compiles C++ extensions) into node extensions is not properly configured?

Are you able to build other node-gyp packages?

**Comment by ricmoo** [comment]
Did you ever resolve this? I will close this shortly unless there are further concerns.
